<?= $this->administrationMenu() ?>
<?= $this->render('partials/posts-menu.phtml'); ?>


<section id="message-form" class="right">
	<?php 
    	$form->setAttribute('action', $this->url('administration/posts/edit', array('id' => $postId)));
    	$form->prepare();
    	$postFieldset	= $form->get('post'); ?>

	<?= $this->form()->openTag($form); ?>
	<?= $this->formCollection($postFieldset->get('keywords')) ?>
	<?= $this->formRow($postFieldset->get('add_keyword')) ?>
	<?= $this->formRow($postFieldset->get('category_id')) ?>
	<?= $this->formRow($postFieldset->get('title')) ?>
	<?= $this->formRow($postFieldset->get('lead')) ?>
	<?= $this->formRow($postFieldset->get('body')) ?>
	<?= $this->formRow($form->get('preview')) ?>
	<?= $this->formSubmit($form->get('submit')) ?>
	<?= $this->formElementerrors($form) ?>
	<?= $this->form()->closeTag($form); ?>
</section>